<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ControlNewDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::connection('alert-system')->table('control_new_data')->insert(
            [
                [
                    'alert_id'          => 1,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 2,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 4,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 5,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 6,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 7,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 8,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 9,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 10,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 11,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 12,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 13,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 14,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 15,
                    'alert_code'        => 'landslide',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 1,
                    'alert_code'        => 'flood',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 2,
                    'alert_code'        => 'flood',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 3,
                    'alert_code'        => 'flood',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 4,
                    'alert_code'        => 'flood',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 5,
                    'alert_code'        => 'flood',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'alert_id'          => 6,
                    'alert_code'        => 'flood',
                    'date'              => '2019-08-13',
                    'time'              => '09:00:00',
                    'active'            => true,
                    'homogenization'    => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ]
            ]
        );
    }
}
